### ISSUE TITLE
Unable to load required framework: ext@null

### ISSUE THREAD

**Issue by Sam-Dvorack** [sencha/ext-react-spotify#1]
I'm getting the below issue when I run the app

i [ext]: [ERR] Directory \build\ext-react\node_modules\@sencha\ext not recognized as a framework
i [ext]: [ERR] Unable to load required framework: ext@null
i [ext]: Completed ext-webpack-plugin processing
× ｢wdm｣: Built at: 10/09/2019 2:41:01 PM
Entrypoint app = app.js app.js.map

ERROR in i [ext]: Directory \build\ext-react\node_modules\@sencha\ext not recognized as a framework

ERROR in i [ext]: Unable to load required framework: ext@null

ERROR in 321
i ｢wdm｣: Failed to compile.

**Comment by maxrahder** [comment]
Hi Sam! I'm guessing you aren't logged into to Sencha's private repo. Can you try logging in again? Copying and pasting your credentials from the Sencha email is a good idea. If that doesn't work, link me your forked copy of the app and I'll try it too.  :-)

**Comment by Sam-Dvorack** [comment]
> Hi Sam! I'm guessing you aren't logged into to Sencha's private repo. Can you try logging in again? Copying and pasting your credentials from the Sencha email is a good idea. If that doesn't work, link me your forked copy of the app and I'll try it too. :-)

![image](https://user-images.githubusercontent.com/47389279/66627116-f1a53c00-ebfa-11e9-8213-f8f7752ffd6f.png)

I did login but still failing to build, I will share the link shortly.

**Comment by Sam-Dvorack** [comment]
@maxrahder 

https://github.com/Sam-Dvorack/ext-react-spotify.git

**Comment by maxrahder** [comment]
Your copy runs for me. Send me an email and maybe we can do a screen share and figure out what's different in our environments. rahder at gmail dot com. :-)

**Comment by Sam-Dvorack** [comment]
Thank you I sent a mail to you.
